/**
 * Model Post
 *
 */
export type Post = {
	/**
	 * The unique identifier for the post
	 * @zod.uuid()
	 * @default {Generated by database}
	 */
	id: string
	/**
	 * A brief title that describes the contents of the post
	 * @zod.max(255, { message: "The title must be shorter than 256 characters" })
	 */
	title: string
	/**
	 * The actual contents of the post.
	 * @zod.max(10240)
	 */
	contents: string
}
